from typing import Dict
from .models import PagodaModel, PagodaUncertainty


def build_pagoda_models() -> Dict[str, PagodaModel]:
    return {
        "yingxian": PagodaModel(
            name="应县木塔",
            dynasty="辽代 (1056年)",
            country="中国",
            height=67.31,
            floor_count=5,
            structural_type="楼阁式木塔 (明5暗9)",
            floor_heights=[6.59, 5.49, 4.99, 4.59, 4.09],
            floor_diameters=[30.27, 22.65, 18.46, 15.28, 12.10],
            inner_diameters=[15.2, 12.0, 10.0, 8.5, 7.0],
            wall_thickness=[2.0, 1.8, 1.6, 1.4, 1.2],
            timber_properties={
                "E_L": 10000.0,
                "E_R": 800.0,
                "E_T": 500.0,
                "density": 500.0,
                "timber_species": "华北落叶松/油松",
                "moisture_content_pct": 12.0,
            },
            joint_properties={
                "rotational_stiffness": 1e8,
                "yield_moment": 1e5,
                "joint_type": "半刚性榫卯连接",
                "tenon_insertion_depth_mm": 300.0,
            },
            seismic_philosophy="以柔克刚：榫卯半刚性连接+斗拱耗能+暗层斜撑三道抗震防线",
            shinbashira=False,
            shinbashira_diameter=0.0,
            data_sources=[
                "陈明达《应县木塔》(1966) - 实测尺寸",
                "太原理工大学《应县木塔结构监测报告》(2020) - 材性试验",
                "GB 50165-92《古建筑木结构维护与加固技术规范》",
                "清华大学土木系《应县木塔动力特性实测》(2014) - f1=0.42~0.48Hz",
            ],
            calibration_year=2020,
            uncertainty=PagodaUncertainty(0.01, 0.02, 0.10, 0.18),
        ),
        "gojunoto_horyuji": PagodaModel(
            name="法隆寺五重塔",
            dynasty="飞鸟时代 (约700年)",
            country="日本",
            height=31.53,
            floor_count=5,
            structural_type="多重塔 (心柱式)",
            floor_heights=[7.82, 6.05, 4.85, 4.12, 3.25],
            floor_diameters=[10.84, 9.28, 7.76, 6.32, 5.04],
            inner_diameters=[3.48, 2.98, 2.48, 1.98, 1.48],
            wall_thickness=[0.82, 0.72, 0.62, 0.52, 0.42],
            timber_properties={
                "E_L": 9500.0,
                "E_R": 650.0,
                "E_T": 420.0,
                "density": 440.0,
                "timber_species": "日本扁柏 (Hinoki)",
                "moisture_content_pct": 13.5,
            },
            joint_properties={
                "rotational_stiffness": 4.5e7,
                "yield_moment": 4.8e4,
                "joint_type": "贯木栓+楔固定",
                "tenon_insertion_depth_mm": 250.0,
            },
            seismic_philosophy="柔性屈服：层间大变形+心柱恢复力+独立屋檐质量调谐",
            shinbashira=True,
            shinbashira_diameter=0.58,
            data_sources=[
                "日本建筑学会《日本古建筑構造》(2018) - 法隆寺第4次修復測量",
                "東京大学地震研究所『五重塔耐震研究』(2015) - f1=0.82~0.91Hz",
                "太田博太郎《日本建築史》(2008) - 心柱構造原理",
                "文化庁『国宝建造物修理工事報告書』(法隆寺, 1985)",
            ],
            calibration_year=2015,
            uncertainty=PagodaUncertainty(0.015, 0.025, 0.12, 0.22),
        ),
        "gojunoto_toji": PagodaModel(
            name="东寺五重塔",
            dynasty="平安时代 (1644年再建)",
            country="日本",
            height=54.80,
            floor_count=5,
            structural_type="多重塔 (心柱式·最高木造塔)",
            floor_heights=[12.50, 10.20, 8.30, 6.90, 5.70],
            floor_diameters=[15.80, 13.50, 11.40, 9.50, 7.80],
            inner_diameters=[4.90, 4.30, 3.70, 3.10, 2.50],
            wall_thickness=[1.25, 1.10, 0.95, 0.80, 0.65],
            timber_properties={
                "E_L": 9200.0,
                "E_R": 620.0,
                "E_T": 400.0,
                "density": 450.0,
                "timber_species": "日本扁柏+松材",
                "moisture_content_pct": 13.0,
            },
            joint_properties={
                "rotational_stiffness": 5.2e7,
                "yield_moment": 5.5e4,
                "joint_type": "贯木栓+大径楔+蝉榫",
                "tenon_insertion_depth_mm": 280.0,
            },
            seismic_philosophy="柔性屈服：高塔高柔心柱+屋檐TMD质量比7.8%+层间累积滑移",
            shinbashira=True,
            shinbashira_diameter=0.72,
            data_sources=[
                "文化庁『東寺五重塔修理工事報告書』(2000) - 精密実測",
                "京都大学耐震工学研究センター『東寺五重塔地震応答解析』(2018)",
                "日本建築学会大会『五重塔の動的挙動に関する研究』(2019) - f1=0.49~0.58Hz",
                "『日本の五重塔 構造と意匠』(彰国社, 2012)",
            ],
            calibration_year=2018,
            uncertainty=PagodaUncertainty(0.018, 0.028, 0.12, 0.24),
        ),
    }
